spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: 
    hibernate:
      ddl-auto: update
  redis: 
    lettuce:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      # pool: 
      #   max-active: 10
      #   max-idle: 10
      #   min-idle: 2
      password: 'abcde'

springdoc:
  swagger-ui:
    path: /api/release/swagger

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL}
aggregator:
  service:
    url: ${AGGREGATOR_SERVICE_URL}
# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update